# Use Azure Open AI with key
provider: autogen_ext.models.openai.AzureOpenAIChatCompletionClient
config:
   model: o4-mini
   azure_endpoint: "https://aq-aoai-swedencentral.openai.azure.com/"
   azure_deployment: o4-mini
   api_version: "2025-03-01-preview"
   api_key: "3ShjYyRHd6t0VthIuoOUe1GEnwlj1tkNSHkOs6IrO1CxKQ3gHmsIJQQJ99BAACfhMk5XJ3w3AAABACOG3ddZ"