#rename to model_config.yaml
# Use Azure Open AI with key
provider: autogen_ext.models.openai.AzureOpenAIChatCompletionClient
config:
   model: your model
   azure_endpoint: "your endpoint"
   azure_deployment: your model deployment name
   api_version: "2025-03-01-preview"
   api_key: "your key"